var language_JSON = {
	"el":{
		"yes":"Ναί",
		"no":"Όχι",
		"areYouSure":"Είσαι σίγουρος/η;",
		"logoutAsk":"Θέλεις να βγείς από το coffeenow;",
		"logoutInfo":"Επίλεξε το \"Έξοδος\" όταν έισαι έτοιμος/η να βγείς",
		"cancel":"Άκυρο",
		"logout":"Έξοδος",
		"deleteInform":"Επίλεξες διαγραφή",
		"insert":"Εισαγωγή",
		"update":"Ενημέρωση",
		"search":"Αναζήτηση",
		"noneSelected":"Κανένα επιλεγμένο",
		"selected":"Επιλεγμένα",
		"allSelected":"Όλα επιλεγμένα",
		"selectAll":"Επιλογή όλων",
		"attention":"Προσοχή",
		"close":"Κλείσιμο",
		"cannotDeleteParentWithChildren":"Δεν μπορείς να διαγράψεις κατηγορία με υποκατηγορίες",
		"dataTableLanguageURL":"//cdn.datatables.net/plug-ins/1.10.19/i18n/Greek.json"
	},
	"en":{
		"yes":"Yes",
		"no":"No",
		"areYouSure":"Are you sure\?",
		"logoutAsk":"Ready to Leave\?",
		"logoutInfo":"Select \"Logout\" below if you are ready to end your current session",
		"cancel":"Cancel",
		"logout":"Logout",
		"deleteInform":"You chose delete",
		"insert":"Insert",
		"update":"Update",
		"search":"Search",
		"noneSelected":"None selected",
		"selected":"Selected",
		"allSelected":"All selected",
		"selectAll":"Select all",
		"attention":"Attention",
		"close":"Close",
		"cannotDeleteParentWithChildren":"You cannot delete a category with children",
		"dataTableLanguageURL":"//cdn.datatables.net/plug-ins/1.10.19/i18n/English.json"
	}
};
var locale = document.getElementById("languagesCFN").getAttribute("data-cfn-locale");